// <auto-generated />
using System;
using ChainDegree.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChainDegree.Infrastructure.Migrations
{
    [DbContext(typeof(ChainDegreeDbContext))]
    [Migration("20260420164155_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChainDegree.Domain.BaoCaoGianLan.Aggregates.BaoCaoGianLan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BangCapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoSoDaoTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LoaiNguoiBaoCao")
                        .HasColumnType("int");

                    b.Property<int>("LyDo")
                        .HasColumnType("int");

                    b.Property<Guid>("NguoiBaoCaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGianBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<Guid?>("XuLyBoiAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BangCapId");

                    b.HasIndex("CoSoDaoTaoId");

                    b.HasIndex("NguoiBaoCaoId");

                    b.ToTable("BaoCaoGianLan", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.DanhMuc.Entities.LinhVuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("LinhVuc", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.QuanLyBangCap.Aggregates.CoSoDaoTao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiViCSDT")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("TKId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TaiKhoanId");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("YeuCauDangKyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YeuCauDangKyId")
                        .IsUnique();

                    b.ToTable("CoSoDaoTao", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.QuanLyBangCap.Entities.BangCap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoSoDaoTaoCapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("File")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("GhiChuHuy")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("GhiChuKhoiPhuc")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("GhiChuThuHoi")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("LinhVucId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("LoaiBangCap")
                        .HasColumnType("int");

                    b.Property<int?>("LyDoHuyBangCap")
                        .HasColumnType("int");

                    b.Property<int?>("LyDoKhoiPhucBangCap")
                        .HasColumnType("int");

                    b.Property<int?>("LyDoThuHoiBangCap")
                        .HasColumnType("int");

                    b.Property<string>("MaBamGiaoDich")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.Property<string>("MaBamXacThuc")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salt")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("SinhVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiBangCapHienTai")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiBlockchainHienTai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoSoDaoTaoCapId");

                    b.HasIndex("LinhVucId");

                    b.HasIndex("MaBamXacThuc")
                        .IsUnique()
                        .HasFilter("[MaBamXacThuc] IS NOT NULL");

                    b.HasIndex("SinhVienId");

                    b.ToTable("BangCap", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.QuanLyBangCap.Entities.SinhVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChiViSinhVien")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<Guid>("TKId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TaiKhoanId");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("TKId")
                        .HasDatabaseName("IX_SinhVien_TaiKhoanId");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.QuanLyToChuc.Aggregates.YeuCauDangKy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiVi")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("GhiChuDuyet")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("GhiChuTuChoi")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<int?>("LyDo")
                        .HasColumnType("int");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenToChuc")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ThoiGianNop")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXetDuyet")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiaChiVi")
                        .HasDatabaseName("IX_YeuCauDangKy_DiaChiVi");

                    b.HasIndex("TaiKhoanId")
                        .HasDatabaseName("IX_YeuCauDangKy_TaiKhoanId");

                    b.ToTable("YeuCauDangKy", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.QuanLyToChuc.Events.CoSoDaoTaoApprovedEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 4, 20, 16, 41, 55, 559, DateTimeKind.Utc).AddTicks(2626));

                    b.Property<string>("DiaChiVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenToChuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("YeuCauDangKyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed", "CreatedAt")
                        .HasDatabaseName("IX_UnprocessedEvents");

                    b.ToTable("CoSoDaoTaoApprovedEvents");
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Aggregates.NhaTuyenDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DiaChiViNhaTuyenDung")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("YeuCauDangKyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("NhaTuyenDung", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.BangCapUngTuyen", b =>
                {
                    b.Property<Guid>("HoSoUngTuyenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BangCapId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HoSoUngTuyenId", "BangCapId");

                    b.HasIndex("BangCapId");

                    b.ToTable("BangCapUngTuyen", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.HoSoUngTuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SinhVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianUngTuyen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ThongTinTuyenDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThaiUngTuyenHienTai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThongTinTuyenDungId");

                    b.HasIndex("SinhVienId", "ThongTinTuyenDungId")
                        .IsUnique()
                        .HasFilter("[ThoiGianXoa] IS NULL");

                    b.ToTable("HoSoUngTuyen", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.KetQuaPhanTich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoSoUngTuyenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KetLuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhanTramPhuHop")
                        .HasColumnType("float");

                    b.Property<DateTime>("ThoiGianPhanTich")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ThongTinTuyenDungId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HoSoUngTuyenId");

                    b.HasIndex("ThongTinTuyenDungId");

                    b.ToTable("KetQuaPhanTich", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.ThongTinTuyenDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LinhVucId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("NhaTuyenDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiHanUngTuyen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LinhVucId");

                    b.HasIndex("NhaTuyenDungId");

                    b.ToTable("ThongTinTuyenDung", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.XacMinhBangCap.Aggregates.NhatKyXacMinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BangCapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KetQuaXacMinh")
                        .HasColumnType("int");

                    b.Property<string>("MaBamXacMinh")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.Property<Guid?>("NhaTuyenDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGianXacMinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BangCapId");

                    b.HasIndex("NhaTuyenDungId");

                    b.ToTable("NhatKyXacMinh", (string)null);
                });

            modelBuilder.Entity("ChainDegree.Domain.BaoCaoGianLan.Aggregates.BaoCaoGianLan", b =>
                {
                    b.HasOne("ChainDegree.Domain.QuanLyBangCap.Aggregates.CoSoDaoTao", null)
                        .WithMany()
                        .HasForeignKey("CoSoDaoTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChainDegree.Domain.QuanLyBangCap.Aggregates.CoSoDaoTao", b =>
                {
                    b.HasOne("ChainDegree.Domain.QuanLyToChuc.Aggregates.YeuCauDangKy", null)
                        .WithOne()
                        .HasForeignKey("ChainDegree.Domain.QuanLyBangCap.Aggregates.CoSoDaoTao", "YeuCauDangKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("ChainDegree.Domain.QuanLyToChuc.ValueObjects.GiayPhepCSDT", "DanhSachGiayPhepCSDT", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CoSoDaoTaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("DuocXacMinhBoiAdminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DuongDanLuuTru")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<int>("LoaiGiayPhep")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ThoiGianDuocXacMinh")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("ThoiGianHetHan")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ThoiGianTaiLen")
                                .HasColumnType("datetime2");

                            b1.Property<int>("TrangThai")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("CoSoDaoTaoId");

                            b1.ToTable("GiayPhepCSDT", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CoSoDaoTaoId");

                            b1.OwnsOne("ChainDegree.Domain.QuanLyToChuc.ValueObjects.ThongTinChuKySo", "ThongTinChuKySoGiayPhepCSDT", b2 =>
                                {
                                    b2.Property<int>("GiayPhepCSDTId")
                                        .HasColumnType("int");

                                    b2.Property<bool>("CoChuKySo")
                                        .HasColumnType("bit")
                                        .HasColumnName("ChuKy_CoChuKySo");

                                    b2.Property<bool>("HopLe")
                                        .HasColumnType("bit")
                                        .HasColumnName("ChuKy_HopLe");

                                    b2.Property<DateTime>("NgayHetHan")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("ChuKy_NgayHetHan");

                                    b2.Property<string>("NhaCungCap")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("ChuKy_NhaCungCap");

                                    b2.Property<bool>("NhaCungCapDuocTinTuong")
                                        .HasColumnType("bit")
                                        .HasColumnName("ChuKy_NhaCungCapDuocTinTuong");

                                    b2.Property<DateTime>("XacMinhLuc")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("ChuKy_XacMinhLuc");

                                    b2.HasKey("GiayPhepCSDTId");

                                    b2.ToTable("GiayPhepCSDT");

                                    b2.WithOwner()
                                        .HasForeignKey("GiayPhepCSDTId");
                                });

                            b1.Navigation("ThongTinChuKySoGiayPhepCSDT");
                        });

                    b.OwnsOne("ChainDegree.Domain.QuanLyToChuc.ValueObjects.UyTinToChuc", "UyTin", b1 =>
                        {
                            b1.Property<Guid>("CoSoDaoTaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DiemUyTin")
                                .HasColumnType("int")
                                .HasColumnName("UyTin_Diem");

                            b1.Property<int>("Hang")
                                .HasColumnType("int")
                                .HasColumnName("UyTin_HangUyTin");

                            b1.Property<int>("SoLuongBangCapBiBaoCaoGianLan")
                                .HasColumnType("int")
                                .HasColumnName("UyTin_SoLuongBangCapBiBaoCaoGianLan");

                            b1.Property<int>("SoLuongBangCapPhatHanh")
                                .HasColumnType("int")
                                .HasColumnName("UyTin_SoLuongBangCapPhatHanh");

                            b1.Property<int>("SoLuongBangCapThuHoi")
                                .HasColumnType("int")
                                .HasColumnName("UyTin_SoLuongBangCapThuHoi");

                            b1.Property<int>("SoLuongGiayPhep")
                                .HasColumnType("int")
                                .HasColumnName("UyTin_SoLuongGiayPhep");

                            b1.Property<int>("SoLuongXacMinhHopLe")
                                .HasColumnType("int")
                                .HasColumnName("UyTin_SoLuongXacMinhHopLe");

                            b1.HasKey("CoSoDaoTaoId");

                            b1.ToTable("CoSoDaoTao");

                            b1.WithOwner()
                                .HasForeignKey("CoSoDaoTaoId");
                        });

                    b.Navigation("DanhSachGiayPhepCSDT");

                    b.Navigation("UyTin")
                        .IsRequired();
                });

            modelBuilder.Entity("ChainDegree.Domain.QuanLyBangCap.Entities.BangCap", b =>
                {
                    b.HasOne("ChainDegree.Domain.QuanLyBangCap.Aggregates.CoSoDaoTao", null)
                        .WithMany()
                        .HasForeignKey("CoSoDaoTaoCapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChainDegree.Domain.DanhMuc.Entities.LinhVuc", null)
                        .WithMany()
                        .HasForeignKey("LinhVucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChainDegree.Domain.QuanLyBangCap.Entities.SinhVien", null)
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChainDegree.Domain.QuanLyToChuc.Aggregates.YeuCauDangKy", b =>
                {
                    b.OwnsMany("ChainDegree.Domain.QuanLyToChuc.ValueObjects.GiayPhepCSDT", "GiayPhepCSDTs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid?>("DuocXacMinhBoiAdminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DuongDanLuuTru")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<int>("LoaiGiayPhep")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ThoiGianDuocXacMinh")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("ThoiGianHetHan")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ThoiGianTaiLen")
                                .HasColumnType("datetime2");

                            b1.Property<int>("TrangThai")
                                .HasColumnType("int");

                            b1.Property<Guid>("YeuCauDangKyId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("YeuCauDangKyId");

                            b1.ToTable("YeuCauDangKy_GiayPhepCSDT", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("YeuCauDangKyId");

                            b1.OwnsOne("ChainDegree.Domain.QuanLyToChuc.ValueObjects.ThongTinChuKySo", "ThongTinChuKySoGiayPhepCSDT", b2 =>
                                {
                                    b2.Property<int>("GiayPhepCSDTId")
                                        .HasColumnType("int");

                                    b2.Property<bool>("CoChuKySo")
                                        .HasColumnType("bit")
                                        .HasColumnName("ChuKy_CoChuKySo");

                                    b2.Property<bool>("HopLe")
                                        .HasColumnType("bit")
                                        .HasColumnName("ChuKy_HopLe");

                                    b2.Property<DateTime>("NgayHetHan")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("ChuKy_NgayHetHan");

                                    b2.Property<string>("NhaCungCap")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("ChuKy_NhaCungCap");

                                    b2.Property<bool>("NhaCungCapDuocTinTuong")
                                        .HasColumnType("bit")
                                        .HasColumnName("ChuKy_NhaCungCapDuocTinTuong");

                                    b2.Property<DateTime>("XacMinhLuc")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("ChuKy_XacMinhLuc");

                                    b2.HasKey("GiayPhepCSDTId");

                                    b2.ToTable("YeuCauDangKy_GiayPhepCSDT");

                                    b2.WithOwner()
                                        .HasForeignKey("GiayPhepCSDTId");
                                });

                            b1.Navigation("ThongTinChuKySoGiayPhepCSDT");
                        });

                    b.OwnsMany("ChainDegree.Domain.QuanLyToChuc.ValueObjects.GiayPhepNhaTuyenDung", "GiayPhepNTDs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DuongDanLuuTru")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<int>("LoaiGiayPhep")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ThoiGianDuocXacMinh")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ThoiGianTaiLen")
                                .HasColumnType("datetime2");

                            b1.Property<int>("TrangThai")
                                .HasColumnType("int");

                            b1.Property<Guid?>("XacMinhBoiAdminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("YeuCauDangKyId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("YeuCauDangKyId");

                            b1.ToTable("YeuCauDangKy_GiayPhepNTD", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("YeuCauDangKyId");
                        });

                    b.Navigation("GiayPhepCSDTs");

                    b.Navigation("GiayPhepNTDs");
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Aggregates.NhaTuyenDung", b =>
                {
                    b.OwnsMany("ChainDegree.Domain.QuanLyToChuc.ValueObjects.GiayPhepNhaTuyenDung", "GiayPheps", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DuongDanLuuTru")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<int>("LoaiGiayPhep")
                                .HasColumnType("int");

                            b1.Property<Guid>("NhaTuyenDungId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ThoiGianDuocXacMinh")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ThoiGianTaiLen")
                                .HasColumnType("datetime2");

                            b1.Property<int>("TrangThai")
                                .HasColumnType("int");

                            b1.Property<Guid?>("XacMinhBoiAdminId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("NhaTuyenDungId");

                            b1.ToTable("NhaTuyenDung_GiayPhepNTD", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NhaTuyenDungId");
                        });

                    b.Navigation("GiayPheps");
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.BangCapUngTuyen", b =>
                {
                    b.HasOne("ChainDegree.Domain.QuanLyBangCap.Entities.BangCap", null)
                        .WithMany()
                        .HasForeignKey("BangCapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChainDegree.Domain.TuyenDung.Entities.HoSoUngTuyen", null)
                        .WithMany("BangCapUngTuyens")
                        .HasForeignKey("HoSoUngTuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.HoSoUngTuyen", b =>
                {
                    b.HasOne("ChainDegree.Domain.QuanLyBangCap.Entities.SinhVien", null)
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChainDegree.Domain.TuyenDung.Entities.ThongTinTuyenDung", null)
                        .WithMany()
                        .HasForeignKey("ThongTinTuyenDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.KetQuaPhanTich", b =>
                {
                    b.HasOne("ChainDegree.Domain.TuyenDung.Entities.HoSoUngTuyen", null)
                        .WithMany()
                        .HasForeignKey("HoSoUngTuyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChainDegree.Domain.TuyenDung.Entities.ThongTinTuyenDung", null)
                        .WithMany()
                        .HasForeignKey("ThongTinTuyenDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.ThongTinTuyenDung", b =>
                {
                    b.HasOne("ChainDegree.Domain.DanhMuc.Entities.LinhVuc", null)
                        .WithMany()
                        .HasForeignKey("LinhVucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChainDegree.Domain.TuyenDung.Aggregates.NhaTuyenDung", null)
                        .WithMany("ThongTinTuyenDungs")
                        .HasForeignKey("NhaTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChainDegree.Domain.XacMinhBangCap.Aggregates.NhatKyXacMinh", b =>
                {
                    b.HasOne("ChainDegree.Domain.TuyenDung.Aggregates.NhaTuyenDung", null)
                        .WithMany()
                        .HasForeignKey("NhaTuyenDungId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Aggregates.NhaTuyenDung", b =>
                {
                    b.Navigation("ThongTinTuyenDungs");
                });

            modelBuilder.Entity("ChainDegree.Domain.TuyenDung.Entities.HoSoUngTuyen", b =>
                {
                    b.Navigation("BangCapUngTuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
