<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChainDegree.SharedKernel\ChainDegree.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="QuanLyToChuc\Interfaces\" />
    <Folder Include="QuanLyToChuc\Services\" />
    <Folder Include="TuyenDung\ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ControlHub.Domain" Version="1.0.8" />
  </ItemGroup>

</Project>
