/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MyWallet, MyWalletInterface } from "../MyWallet.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "deposite",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getBalance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "withdrawAll",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b505f80546001600160a01b031916331790556102408061002d5f395ff3fe608060405260043610610049575f3560e01c806312065fe01461004d5780632e1a7d4d1461006c578063853828b61461008d5780638da5cb5b146100a1578063a50ec3261461008b575b5f5ffd5b348015610058575f5ffd5b506040514781526020015b60405180910390f35b348015610077575f5ffd5b5061008b6100863660046101f3565b6100d7565b005b348015610098575f5ffd5b5061008b61015b565b3480156100ac575f5ffd5b505f546100bf906001600160a01b031681565b6040516001600160a01b039091168152602001610063565b5f546001600160a01b0316331461012d5760405162461bcd60e51b81526020600482015260156024820152742cb7ba9030b932903737ba103a34329037bbb732b960591b60448201526064015b60405180910390fd5b604051339082156108fc029083905f818181858888f19350505050158015610157573d5f5f3e3d5ffd5b5050565b5f546001600160a01b031633146101ac5760405162461bcd60e51b81526020600482015260156024820152742cb7ba9030b932903737ba103a34329037bbb732b960591b6044820152606401610124565b478061012d5760405162461bcd60e51b81526020600482015260166024820152754e6f2062616c616e636520746f20776974686472617760501b6044820152606401610124565b5f60208284031215610203575f5ffd5b503591905056fea26469706673582212207d9e4d42f19d7e269a9fb5cb566735f22c9e58a6a59802a727fda18f38a6889464736f6c634300081c0033";

  
      type MyWalletConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MyWalletConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MyWallet__factory extends ContractFactory {
    
      constructor(...args: MyWalletConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MyWallet & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MyWallet__factory {
      return super.connect(runner) as MyWallet__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MyWalletInterface {
      return new Interface(_abi) as MyWalletInterface;
    }
    
    override attach(address: string | Addressable): MyWallet {
      return super.attach(address) as MyWallet;
    }
  static connect(address: string, runner?: ContractRunner | null): MyWallet {
      return new Contract(address, _abi, runner) as unknown as MyWallet;
    }
  }

  
  