[Node]
data-path="/opt/besu/data"

[Rpc]
http-enabled=true
http-host="0.0.0.0"
http-port=8545
http-api=["ETH","NET","IBFT","WEB3","ADMIN","TXPOOL"]
http-cors-origins=["*"]

[P2p]
port=30303

[Mining]
miner-enabled=false

[Sync]
sync-mode="FULL"

[Logging]
log-level="INFO"
